# Generated by Django 3.2.1 on 2021-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='friend_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, upload_to='user_avatar'),
        ),
    ]
