# Generated by Django 3.2.1 on 2021-06-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_image'),
        ),
    ]
