# Generated by Django 3.2.1 on 2021-06-23 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_sns_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sns_comments',
            name='id',
        ),
        migrations.AddField(
            model_name='sns_comments',
            name='cid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
