# Generated by Django 3.2.1 on 2021-06-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0004_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=models.TextField(),
        ),
    ]
