# Generated by Django 3.2.1 on 2021-06-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0005_alter_recipe_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.TextField(),
        ),
    ]
